1. Project Introduction
2. Import Libraries
3. Define Data Parameters
4. Download Gold Price Data
5. Initial Inspection
6. Save Raw Data

# Gold Volatility Analysis

## Objective

This project analyzes the historical price behavior and volatility of gold.

The main objectives are:

- Analyze historical gold prices
- Calculate daily and log returns
- Measure historical and rolling volatility
- Investigate volatility clustering
- Model volatility using GARCH
- Evaluate market risk using VaR and Expected Shortfall

The analysis is designed as a financial analytics and quantitative research project.

## Phase 1 — Data Collection

In this phase, historical gold price data is collected and stored as raw data.

No financial transformations are performed at this stage.

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path
import yfinance as yf

In [2]:
BASE_DIR = Path.cwd().parent

RAW_DIR = BASE_DIR / "Data" / "raw"
PROCESSED_DIR = BASE_DIR / "Data" / "processed"

RAW_DIR.mkdir(parents=True, exist_ok=True)
PROCESSED_DIR.mkdir(parents=True, exist_ok=True)

print("Raw data path:", RAW_DIR)
print("Processed data path:", PROCESSED_DIR)

Raw data path: c:\Users\r\Documents\GitHub\Gold-Volatility-Analysis\Data\raw
Processed data path: c:\Users\r\Documents\GitHub\Gold-Volatility-Analysis\Data\processed

## Download Gold Futures Data

Gold futures historical data is collected from Yahoo Finance using
the ticker symbol `GC=F`.

The dataset contains daily OHLC prices, adjusted closing price,
and trading volume.

In [4]:
ticker = "GC=F"

gold_df = yf.download(
    ticker,
    start="2010-01-01",
    progress=False,
    auto_adjust=False
)

gold_df.head()

Price,Adj Close,Close,High,Low,Open,Volume
Ticker,GC=F,GC=F,GC=F,GC=F,GC=F,GC=F
Date,,,,,,
2010-01-04,1117.699951,1117.699951,1122.300049,1097.099976,1117.699951,184
2010-01-05,1118.099976,1118.099976,1126.500000,1115.000000,1118.099976,53
2010-01-06,1135.900024,1135.900024,1139.199951,1120.699951,1135.900024,363
2010-01-07,1133.099976,1133.099976,1133.099976,1129.199951,1133.099976,56
2010-01-08,1138.199951,1138.199951,1138.199951,1122.699951,1138.199951,54

In [5]:
print("Shape:", gold_df.shape)
print("\nColumns:")
print(gold_df.columns)

print("\nMissing Values:")
print(gold_df.isnull().sum())

gold_df.info()

Shape: (4207, 6)

Columns:
MultiIndex([('Adj Close', 'GC=F'),
            (    'Close', 'GC=F'),
            (     'High', 'GC=F'),
            (      'Low', 'GC=F'),
            (     'Open', 'GC=F'),
            (   'Volume', 'GC=F')],
           names=['Price', 'Ticker'])

Missing Values:
Price      Ticker
Adj Close  GC=F      0
Close      GC=F      0
High       GC=F      0
Low        GC=F      0
Open       GC=F      0
Volume     GC=F      0
dtype: int64
<class 'pandas.DataFrame'>
DatetimeIndex: 4207 entries, 2010-01-04 to 2026-09-24
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   (Adj Close, GC=F)  4207 non-null   float64
 1   (Close, GC=F)      4207 non-null   float64
 2   (High, GC=F)       4207 non-null   float64
 3   (Low, GC=F)        4207 non-null   float64
 4   (Open, GC=F)       4207 non-null   float64
 5   (Volume, GC=F)     4207 non-null   int64
dtypes: float64(5), int64(1)
memory usage: 230.1 KB

In [6]:
display(gold_df.head())

display(gold_df.tail())

Price,Adj Close,Close,High,Low,Open,Volume
Ticker,GC=F,GC=F,GC=F,GC=F,GC=F,GC=F
Date,,,,,,
2010-01-04,1117.699951,1117.699951,1122.300049,1097.099976,1117.699951,184
2010-01-05,1118.099976,1118.099976,1126.500000,1115.000000,1118.099976,53
2010-01-06,1135.900024,1135.900024,1139.199951,1120.699951,1135.900024,363
2010-01-07,1133.099976,1133.099976,1133.099976,1129.199951,1133.099976,56
2010-01-08,1138.199951,1138.199951,1138.199951,1122.699951,1138.199951,54

Price,Adj Close,Close,High,Low,Open,Volume
Ticker,GC=F,GC=F,GC=F,GC=F,GC=F,GC=F
Date,,,,,,
2026-09-18,4424.899902,4424.899902,4439.799805,4372.200195,4381.600098,142919
2026-09-21,4383.899902,4383.899902,4422.100098,4360.299805,4413.000000,138203
2026-09-22,4376.399902,4376.399902,4414.100098,4327.600098,4382.500000,178132
2026-09-23,4318.399902,4318.399902,4407.500000,4310.700195,4394.700195,178132
2026-09-24,4307.399902,4307.399902,4338.000000,4278.299805,4324.399902,158403

In [7]:
output_file = RAW_DIR / "gold_price.csv"

gold_df.to_csv(output_file)

print(f"File saved successfully:\n{output_file}")

File saved successfully:
c:\Users\r\Documents\GitHub\Gold-Volatility-Analysis\Data\raw\gold_price.csv

## Phase 1 Summary

Historical gold futures data was successfully collected from Yahoo Finance
using the ticker symbol `GC=F`.

The raw dataset has been stored without any transformations and will be
used in subsequent phases for cleaning, return calculation, volatility
analysis, and risk modeling.

In [8]:
gold_df.shape

gold_df.head()

gold_df.tail()

gold_df.isnull().sum()

Price      Ticker
Adj Close  GC=F      0
Close      GC=F      0
High       GC=F      0
Low        GC=F      0
Open       GC=F      0
Volume     GC=F      0
dtype: int64